# Generated by Django 4.2 on 2023-04-28 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionComptes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
