# Generated by Django 4.2 on 2023-04-10 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('action', 'Action'), ('aventure', 'Aventure'), ('comédie', 'Comédie'), ('drame', 'Drame'), ('ecchi', 'Ecchi'), ('fantaisie', 'Fantaisie'), ('horreur', 'Horreur'), ('mecha', 'Mecha'), ('romance', 'Romance'), ('science-fiction', 'Science-fiction'), ('slice-of-life', 'Slice of life'), ('sport', 'Sport'), ('yaoi', 'Yaoi'), ('yuri', 'Yuri'), ('shonen-ai', 'Shonen-ai'), ('shoujo-ai', 'Shoujo-ai'), ('magical-girl', 'Magical girl'), ('harem', 'Harem'), ('isekai', 'Isekai'), ('historique', 'Historique'), ('mystère', 'Mystère'), ('psychologique', 'Psychologique'), ('tranche-de-vie', 'Tranche de vie')], max_length=100, verbose_name='Genre')),
                ('slug', models.SlugField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='MangaWiki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=40, verbose_name='Auteur')),
                ('number_of_volume', models.IntegerField(verbose_name='Nombre de volume')),
                ('status', models.CharField(choices=[('non-lu', 'Non lu'), ('en-cours', 'En cours'), ('lu', 'Lu')], max_length=100, verbose_name='Etat de Lecture')),
                ('note', models.TextField(max_length=25)),
                ('title', models.CharField(max_length=60, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True)),
                ('description', models.TextField(max_length=155, verbose_name='Description')),
                ('collection_author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('gender', models.ManyToManyField(to='Collection.gender')),
            ],
        ),
    ]
