# Generated by Django 4.2 on 2023-04-10 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Collection', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mangawiki',
            options={'ordering': ['status'], 'verbose_name': 'Manga Collection'},
        ),
    ]
