# Generated by Django 4.2 on 2023-04-10 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Collection', '0002_alter_mangawiki_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mangawiki',
            name='gender',
            field=models.ManyToManyField(blank=True, to='Collection.gender'),
        ),
    ]
