# Generated by Django 4.2 on 2023-04-28 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Collection', '0003_alter_mangawiki_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mangawiki',
            name='description',
            field=models.TextField(max_length=655, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='mangawiki',
            name='note',
            field=models.TextField(max_length=150),
        ),
    ]
